spring:
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD_CONFIG_SERVER_GIT_URI}
          username: ${CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${CLOUD_CONFIG_SERVER_GIT_PASSWORD}
server:
  port: 80
