server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CLOUD_CONFIG_SERVER_GIT_URI}
          username: ${CLOUD_CONFIG_SERVER_GIT_USERNAME}
          password: ${CLOUD_CONFIG_SERVER_GIT_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA}
  instance:
    preferIpAddress: true
