spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bstrdn/config-repo
          username: bstrdn
          password:
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.88.222:8761/eureka
  instance:
    preferIpAddress: true

server:
  port: 8888
